---
- name: test
  hosts: all

  tasks:
    - name: test connection
      ansible.windows.win_ping:
        
    - name: Build Image
      ansible.windows.win_powershell:
        script: |
          cd "C:\users\m.wolosz\Desktop\Docker\Portal\"
          docker build -t webconansible:232 .

    - name: Summary
      debug:
        msg: 
        - "Docker image created"
